name: DS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - requests
  - notebook
  - ipykernel
  - pip
  - pip:
    - jupyter
    - scikit-learn
  - seaborn
  - xgboost
    
